version: '3.8'

services: 
    app:
        image: dima95/itrex-laba-project 
        command: npm start
        working_dir: /usr/src/app
        volumes:
            - ./:/itrex-laba-project
        ports: 
            - 3000:3000
        environment: 
            NODE_ENV: dev
            STORAGE_TYPE: mySQL
            DEV_APP_PORT: 3000
        depends_on: [mysql_server, redis]
    mysql_server:
        image: mysql:8.0
        restart: always
        volumes:
            - dbdata:/var/lib/mysql
        environment: 
            - MYSQL_PASSWORD=dimozzz_4el
            - MYSQL_ROOT_PASSWORD=dimozzz_4el
            - MYSQL_DATABASE=HOSPITAL
    redis:
        image: redis:6.2
        restart: always
volumes:
    dbdata:

